spring.application.name=blogging_Application


spring.datasource.url=jdbc:mysql://localhost:3306/blogging_app
spring.datasource.username=root
spring.datasource.password=sandilya@1704

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
cloudinary.cloud-name=dlgconod5
cloudinary.api-key=424522625544587
cloudinary.api-secret=jUFWuIu31JCW6fz_MFVZd7bwA38
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB